version: '3.7'

services:
  lora_db:
    image: postgres:9.5
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: lorawan
      POSTGRES_USER: lora
      POSTGRES_DB: loradb
  django:
    container_name: dj_lora
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/dj_lora
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - lora_db
volumes:
  pg_data:
