# Generated by Django 3.0.4 on 2020-09-10 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lora_networks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='getaway',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='lora_networks.Getaway'),
        ),
    ]
