# Generated by Django 3.0.4 on 2020-09-10 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lora_networks', '0002_auto_20200910_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='lora_networks.Node'),
        ),
        migrations.AlterField(
            model_name='device_info',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataList', to='lora_networks.Device'),
        ),
    ]
