# Generated by Django 3.1.2 on 2020-11-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lora_networks', '0004_auto_20200911_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='description',
            field=models.CharField(blank=True, max_length=150, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='node',
            name='nick',
            field=models.CharField(blank=True, max_length=50, verbose_name='nick'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=36, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=24, verbose_name='Node'),
        ),
    ]
